const WORKFLOW_STATES = {
  APPLIED: 'Applied',
  ACK_SENT: 'Ack Sent',
  DOCS_PENDING: 'Docs Pending',
  DOCS_COMPLETE: 'Docs Complete',
  FOR_REVIEW: 'For Review',
  SHORTLISTED: 'Shortlisted',
  INTERVIEW_SCHEDULED: 'Interview Scheduled',
  HIRED: 'Hired',
  REJECTED: 'Rejected'
};

const TRANSITIONS = {
  [WORKFLOW_STATES.APPLIED]: [WORKFLOW_STATES.ACK_SENT, WORKFLOW_STATES.REJECTED],
  [WORKFLOW_STATES.ACK_SENT]: [WORKFLOW_STATES.DOCS_PENDING, WORKFLOW_STATES.REJECTED],
  [WORKFLOW_STATES.DOCS_PENDING]: [WORKFLOW_STATES.DOCS_COMPLETE, WORKFLOW_STATES.REJECTED],
  [WORKFLOW_STATES.DOCS_COMPLETE]: [WORKFLOW_STATES.FOR_REVIEW, WORKFLOW_STATES.REJECTED],
  [WORKFLOW_STATES.FOR_REVIEW]: [WORKFLOW_STATES.SHORTLISTED, WORKFLOW_STATES.REJECTED],
  [WORKFLOW_STATES.SHORTLISTED]: [WORKFLOW_STATES.INTERVIEW_SCHEDULED, WORKFLOW_STATES.REJECTED],
  [WORKFLOW_STATES.INTERVIEW_SCHEDULED]: [WORKFLOW_STATES.HIRED, WORKFLOW_STATES.REJECTED],
  [WORKFLOW_STATES.HIRED]: [],
  [WORKFLOW_STATES.REJECTED]: []
};

const DEFAULT_REQUIRED_DOCUMENTS = [
  'Letter of Intent',
  'PDS',
  'WES',
  'Training/Seminar Certificates',
  'Awards from Last Promotion',
  'Latest IPCR',
  'Proof of CSC Eligibility'
];

const POSITION_CHECKLISTS = {
  default: DEFAULT_REQUIRED_DOCUMENTS,
  'Administrative Assistant I (Computer Operator I)': [
    ...DEFAULT_REQUIRED_DOCUMENTS,
    'Computer Skill Evidence'
  ]
};

const SCORING_WEIGHTS = {
  docsComplete: 30,
  eligibility: 20,
  experience: 20,
  education: 15,
  trainings: 10,
  awards: 5
};

const SCORING_MULTIPLIERS = {
  TRAININGS_PARTIAL_CREDIT: 0.2
};

module.exports = {
  WORKFLOW_STATES,
  TRANSITIONS,
  POSITION_CHECKLISTS,
  DEFAULT_REQUIRED_DOCUMENTS,
  SCORING_WEIGHTS,
  SCORING_MULTIPLIERS
};
